### ISSUE TITLE
Typescript Class methods not higlighted

### ISSUE THREAD

**Issue by mentos1386** [koenverburg/peepsight.nvim#2]
Hey, awesome project!

I expected class methods to be also highlighted. After a bit of trial-and-error using different keywords from [1] i managed to find out that using `method_definition` correctly highlights class methods.

It can be tested on the following example:
```ts
class Foo {
  bar() { // Should be highlighted
    const baz = 42;
  }
}
```

Maybe it should be added to defaults or mentioned in readme?

[1] https://github.com/tree-sitter/tree-sitter-typescript/blob/master/common/define-grammar.js

**Comment by koenverburg** [comment]
Hey @mentos1386,

Thank you for calling this out, I have added it to the example in the read as well as added the grammar link.
