### ISSUE TITLE
Support other languages

### ISSUE THREAD

**Issue by kair8m** [koenverburg/peepsight.nvim#3]
Hi there 😃 
Do you have plans to enhance the plugin by adding support for other languages (eg. C/C++, python, Rust)?

**Comment by koenverburg** [comment]
Hey @kair8m,

You should be able to add the treesitter node types to the config for other languages.

You can find those by installing [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) and [nvim-treesitter/playground](https://github.com/nvim-treesitter/playground) and then using the Playground to look for the function types for your language of choose.

Like here in the example, I have Go and Typescript (which also works for javascript)

```lua
require('peepsight').setup({
  -- go
  "function_declaration",
  "method_declaration",
  "func_literal",

  -- typescript
  "class_declaration",
  "method_definition",
  "arrow_function",
  "function_declaration",
  "generator_function_declaration"
})
```

Let me know if it works, and you have to have the treesitter grammar installed for the language you want to use.

**Comment by jluzny** [comment]
Just for a record: `Decl` node type works for Zig language.
